import { useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { Check, ChevronLeft, ChevronRight, MapPin, ShoppingBag } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { LocationPicker } from "@/components/delivery/LocationPicker";
import { useAppStore } from "@/lib/app-store";
import { formatM, unitLabel } from "@/lib/format";
import type { DeliveryAddress, PaymentMethod } from "@/lib/types";

type Method=PaymentMethod;
export function CheckoutWizard(){
 const s=useAppStore();const navigate=useNavigate();const [step,setStep]=useState(0);const [addressId,setAddressId]=useState(s.savedAddresses[0]?.id??"new");const [address,setAddress]=useState<DeliveryAddress>(s.savedAddresses[0]??{area:s.deliveryArea,address:""});const [name,setName]=useState(s.account.name);const [phone,setPhone]=useState(s.account.phone);const [email,setEmail]=useState(s.account.email??"");const [method,setMethod]=useState<Method>(s.shop.paymentOptions.cashOnDelivery?"cash_on_delivery":s.shop.paymentOptions.mobileMoney?"mobile_money":"card");const [provider,setProvider]=useState("EcoCash");const [cashGiven,setCashGiven]=useState("");const [saveAddress,setSaveAddress]=useState(false);const [error,setError]=useState("");
 const total=s.cartSubtotal+s.shop.deliveryFee;const available=s.cart.map(i=>({item:i,product:s.products.find(p=>p.id===i.productId)}));const unavailable=available.filter(x=>!x.product||!x.product.available||x.product.stock<=0||x.item.quantity>x.product.stock);
 const chosenAddress=addressId==="new"?address:(s.savedAddresses.find(a=>a.id===addressId)??address);
 const setDelivery=(next:DeliveryAddress)=>{setAddress(next);setAddressId("new");};
 const allowed=(key:Method)=>key==="mobile_money"?s.shop.paymentOptions.mobileMoney:key==="cash_on_delivery"?s.shop.paymentOptions.cashOnDelivery:s.shop.paymentOptions.card;
 const continueStep=()=>{setError("");if(step===0){if(!name.trim()||!phone.trim()){setError("Add your name and phone number.");return;}if(!chosenAddress.area||!chosenAddress.address.trim()){setError("Choose a delivery area and add a house, street, or familiar place name.");return;}if(!s.shop.deliveryAreas.includes(chosenAddress.area)){setError("That area is outside the current delivery service area.");return;}}
 if(step===1){if(!allowed(method)){setError("Choose a payment option offered by the shop.");return;}if(method==="cash_on_delivery"&&cashGiven&&Number(cashGiven)<total){setError("Cash available must cover the order total.");return;}}
 setStep(Math.min(2,step+1));};
 const place=()=>{setError("");if(s.cart.length===0){setError("Your cart is empty.");return;}if(s.cartSubtotal<s.shop.minimumOrder){setError(`The minimum order is ${formatM(s.shop.minimumOrder)}.`);return;}if(unavailable.length){setError(`Please remove unavailable or over-stock items: ${unavailable.map(x=>x.item.name).join(", ")}.`);return;}
 const payment={method,provider:method==="mobile_money"?provider:undefined,status:method==="cash_on_delivery"?"unpaid" as const:"pending" as const,cashGiven:method==="cash_on_delivery"&&cashGiven?Number(cashGiven):undefined,exactAmount:method==="cash_on_delivery"?cashGiven==="":undefined};
 const finalAddress={...chosenAddress};const order=s.placeOrder({customer:{name:name.trim(),phone:phone.trim(),email:email.trim()||undefined},address:finalAddress,payment});
 if(saveAddress&&finalAddress.address.trim())s.saveAddress({...finalAddress,id:finalAddress.id??crypto.randomUUID(),label:finalAddress.label||"Home"});
 void navigate({to:"/order-confirmation/$id",params:{id:order.id}});
 };
 if(s.cart.length===0)return <main className="mx-auto max-w-xl px-4 py-16 text-center"><ShoppingBag className="mx-auto size-10 text-primary"/><h1 className="mt-4 text-2xl font-bold">Your cart is empty</h1><p className="mt-2 text-muted-foreground">Add a few groceries to get started.</p><Link to="/shop"><Button className="mt-5">Browse groceries</Button></Link></main>;
 return <main className="mx-auto max-w-6xl px-4 py-7 md:px-8 md:py-10"><div className="mb-6"><Link to="/cart" className="inline-flex items-center gap-1 text-sm font-medium text-muted-foreground hover:text-primary"><ChevronLeft className="size-4"/>Back to cart</Link><h1 className="mt-4 text-3xl font-bold tracking-tight">Checkout</h1><p className="mt-1 text-muted-foreground">A few details and your groceries are on their way.</p></div>
 <ol aria-label="Checkout progress" className="mb-8 grid grid-cols-3">{["Delivery","Payment","Review"].map((label,i)=><li key={label} className={`border-b-2 pb-3 text-sm font-semibold ${i<=step?"border-primary text-primary":"border-border text-muted-foreground"}`}><span className="mr-2 inline-grid size-6 place-items-center rounded-full bg-muted text-xs">{i<step?<Check className="size-4"/>:i+1}</span>{label}</li>)}</ol>
 <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_360px]"><section className="min-w-0">
 {step===0&&<div className="space-y-6"><section><h2 className="text-xl font-semibold">Who is receiving the order?</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Full name<Input required className="mt-1.5" value={name} onChange={e=>setName(e.target.value)}/></label><label className="text-sm font-medium">Phone number<Input required type="tel" className="mt-1.5" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="text-sm font-medium sm:col-span-2">Email (optional)<Input type="email" className="mt-1.5" value={email} onChange={e=>setEmail(e.target.value)}/></label></div></section>
 <section><h2 className="text-xl font-semibold">Where should we deliver?</h2><p className="mt-1 text-sm text-muted-foreground">A familiar place name or landmark is fine. The location pin is optional.</p>{s.savedAddresses.length>0&&<div className="my-4 flex flex-wrap gap-2">{s.savedAddresses.map(a=><button key={a.id} type="button" onClick={()=>setAddressId(a.id??"new")} className={`rounded-xl border px-3 py-2 text-sm ${addressId===a.id?"border-primary bg-emerald-50 text-primary":"bg-card"}`}><MapPin className="mr-1 inline size-3.5"/>{a.label||a.area}</button>)}<button type="button" onClick={()=>{setAddressId("new");setAddress({area:s.deliveryArea,address:""});}} className={`rounded-xl border px-3 py-2 text-sm ${addressId==="new"?"border-primary bg-emerald-50 text-primary":"bg-card"}`}>+ New address</button></div>}
 {addressId==="new"?<LocationPicker value={address} areas={s.shop.deliveryAreas} onChange={setDelivery}/>:<div className="rounded-xl border bg-card p-4"><p className="font-semibold">{chosenAddress.address}</p><p className="text-sm text-muted-foreground">{chosenAddress.area}{chosenAddress.landmark?` · Near ${chosenAddress.landmark}`:""}</p><Button className="mt-3" size="sm" variant="outline" onClick={()=>{setAddress(chosenAddress);setAddressId("new")}}>Edit address</Button></div>}
 <label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={saveAddress} onChange={e=>setSaveAddress(e.target.checked)} className="size-4 accent-primary"/>Save this address for next time</label></section></div>}
 {step===1&&<section><h2 className="text-xl font-semibold">How would you like to pay?</h2><p className="mb-4 mt-1 text-sm text-muted-foreground">Select an option available from {s.shop.name}.</p><div className="space-y-3">{([["cash_on_delivery","Cash on delivery","Pay your driver when the order arrives."],["mobile_money","Mobile money","Pay using EcoCash or M-Pesa."],["card","Card","Card processing is not connected in this demo."]] as [Method,string,string][]).filter(([key])=>allowed(key)).map(([key,title,desc])=><label key={key} className={`block cursor-pointer rounded-2xl border p-4 ${method===key?"border-primary bg-emerald-50/60":"bg-card"}`}><span className="flex items-center gap-3"><input type="radio" name="payment" checked={method===key} onChange={()=>setMethod(key)} className="accent-primary"/><span><span className="block font-semibold">{title}</span><span className="text-sm text-muted-foreground">{desc}</span></span></span></label>)}</div>{method==="mobile_money"&&<label className="mt-4 block text-sm font-medium">Mobile money provider<select className="mt-1.5 h-11 w-full rounded-xl border bg-background px-3" value={provider} onChange={e=>setProvider(e.target.value)}><option>EcoCash</option><option>M-Pesa</option><option>Other mobile money</option></select></label>}{method==="cash_on_delivery"&&<><label className="mt-4 block text-sm font-medium">Cash amount (optional)<Input className="mt-1.5 max-w-xs" type="number" min={total} step="0.01" placeholder="Leave blank for exact amount" value={cashGiven} onChange={e=>setCashGiven(e.target.value)}/></label>{cashGiven&&Number(cashGiven)>=total&&<p className="mt-2 text-sm text-muted-foreground">Your driver should bring {formatM(Number(cashGiven)-total)} change.</p>}</>}<p className="mt-4 rounded-xl bg-muted p-3 text-sm text-muted-foreground">{method==="mobile_money"?"Payment is marked pending. This demo does not initiate a mobile money transfer.":method==="cash_on_delivery"?"Your driver collects payment at delivery. No online payment is taken.":"Card payments are not connected; this demo records the selection as pending."}</p></section>}
 {step===2&&<section><h2 className="text-xl font-semibold">Check your order</h2><div className="mt-4 rounded-2xl border bg-card p-5"><h3 className="font-semibold">Delivery</h3><p className="mt-1">{name} · {phone}</p><p className="text-sm text-muted-foreground">{chosenAddress.address}, {chosenAddress.area}</p>{chosenAddress.landmark&&<p className="text-sm text-muted-foreground">Near {chosenAddress.landmark}</p>}{chosenAddress.instructions&&<p className="text-sm text-muted-foreground">Driver directions: {chosenAddress.instructions}</p>}<Button variant="link" className="h-auto px-0 py-2" onClick={()=>setStep(0)}>Change delivery details</Button><div className="mt-3 border-t pt-3"><h3 className="font-semibold">Payment</h3><p className="mt-1 text-sm text-muted-foreground">{method==="mobile_money"?`${provider} · payment pending`:method==="cash_on_delivery"?`Cash on delivery${cashGiven?` · bring ${formatM(Number(cashGiven))}${Number(cashGiven)>total?` · change ${formatM(Number(cashGiven)-total)}`:""}`:" · exact amount if possible"}`:"Card · pending"}</p><Button variant="link" className="h-auto px-0 py-2" onClick={()=>setStep(1)}>Change payment</Button></div></div>{unavailable.length>0&&<p role="alert" className="mt-4 rounded-xl bg-destructive/10 p-3 text-sm text-destructive">Review stock for: {unavailable.map(x=>x.item.name).join(", ")}.</p>}</section>}
 {error&&<p role="alert" className="mt-5 rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
 <div className="mt-6 flex justify-between gap-3">{step>0?<Button variant="outline" onClick={()=>{setError("");setStep(step-1)}}><ChevronLeft className="size-4"/>Back</Button>:<span/>}{step<2?<Button onClick={continueStep}>Continue<ChevronRight className="size-4"/></Button>:<Button onClick={place}>Place order · {formatM(total)}</Button>}</div></section>
 <aside className="h-fit rounded-2xl border bg-card p-5 lg:sticky lg:top-6"><h2 className="text-lg font-semibold">Your groceries</h2><ul className="mt-4 divide-y">{s.cart.map(item=><li key={item.productId} className="flex justify-between gap-3 py-3 text-sm"><span>{item.quantity} × {item.name}<span className="block text-xs text-muted-foreground">{unitLabel(item.unit)}</span></span><span className="font-semibold">{formatM(item.unitPrice*item.quantity)}</span></li>)}</ul><div className="space-y-2 border-t pt-4 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Subtotal</span><span>{formatM(s.cartSubtotal)}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Delivery</span><span>{formatM(s.shop.deliveryFee)}</span></div><div className="flex justify-between border-t pt-3 text-base font-bold"><span>Total</span><span>{formatM(total)}</span></div></div><p className="mt-4 rounded-xl bg-muted p-3 text-xs text-muted-foreground">{s.cartSubtotal<s.shop.minimumOrder?`Minimum order is ${formatM(s.shop.minimumOrder)}.`:`Delivery to ${chosenAddress.area||s.deliveryArea}.`}</p></aside></div></main>;
}
