import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { Heart, MapPin, Package, UserRound, Bell, Trash2, ShoppingBag, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAppStore, ORDER_STATUS_LABEL, PAYMENT_LABEL } from "@/lib/app-store";
import { formatDate, formatM } from "@/lib/format";
import type { DeliveryAddress } from "@/lib/types";

const sections = [["profile","Profile",UserRound],["addresses","Addresses",MapPin],["orders","Orders",Package],["favourites","Favourites",Heart],["preferences","Preferences",Bell]] as const;
type Section = (typeof sections)[number][0];
export function CustomerAccount({ initialSection="profile" }:{initialSection?:Section}) {
 const s=useAppStore(); const [section,setSection]=useState<Section>(initialSection); const [notice,setNotice]=useState("");
 const myOrders=s.orders.filter(o=>o.customer.customerId===s.account.customerId || (!o.customer.customerId && o.customer.phone===s.account.phone));
 const saveProfile=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);s.updateAccount({name:String(data.get("name")),phone:String(data.get("phone")),email:String(data.get("email"))});setNotice("Your details are saved in this browser.");};
 return <main className="mx-auto max-w-6xl px-4 py-7 md:px-8 md:py-10"><header className="mb-7"><p className="text-sm font-semibold text-primary">YOUR MABOTE FRESH ACCOUNT</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Hello, {s.account.name.split(" ")[0]}</h1><p className="mt-1 text-muted-foreground">Manage the details that make your next shop easier.</p></header>
 <div className="grid gap-7 md:grid-cols-[220px_minmax(0,1fr)]"><nav aria-label="Account sections" className="flex gap-2 overflow-auto md:flex-col">{sections.map(([id,label,Icon])=><button key={id} onClick={()=>setSection(id)} aria-current={section===id?"page":undefined} className={`flex shrink-0 items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold ${section===id?"bg-primary text-primary-foreground":"bg-card hover:bg-muted"}`}><Icon className="size-4"/>{label}</button>)}</nav>
 <div className="min-w-0">{notice&&<p role="status" className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm text-primary">{notice}</p>}
 {section==="profile"&&<section className="max-w-xl"><h2 className="text-xl font-semibold">Your details</h2><p className="mb-5 text-sm text-muted-foreground">We use these details to keep you updated about your order.</p><form onSubmit={saveProfile} className="space-y-4"><label className="block text-sm font-medium">Full name<Input name="name" required defaultValue={s.account.name} className="mt-1.5"/></label><label className="block text-sm font-medium">Phone number<Input name="phone" required type="tel" defaultValue={s.account.phone} className="mt-1.5"/></label><label className="block text-sm font-medium">Email (optional)<Input name="email" type="email" defaultValue={s.account.email??""} className="mt-1.5"/></label><Button>Save details</Button></form><p className="mt-5 text-xs text-muted-foreground">This demo account is stored on this device. Account sign-in is not connected.</p></section>}
 {section==="addresses"&&<AddressBook/>}
 {section==="orders"&&<section><div className="mb-4 flex items-end justify-between"><div><h2 className="text-xl font-semibold">Your orders</h2><p className="text-sm text-muted-foreground">Updates reflect the latest status saved by the shop.</p></div><Link to="/shop" className="text-sm font-semibold text-primary">Shop products</Link></div>{myOrders.length?<div className="space-y-4">{myOrders.map(order=><article key={order.id} className="rounded-2xl border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{order.number}</h3><p className="text-sm text-muted-foreground">{formatDate(order.createdAt)} · {order.address.area}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-sm font-semibold text-primary">{ORDER_STATUS_LABEL[order.status]}</span></div><p className="mt-4 text-sm">{order.items.map(i=>`${i.quantity} × ${i.name}`).join(" · ")}</p><div className="mt-3 flex flex-wrap items-center justify-between gap-3 border-t pt-3"><span className="text-sm text-muted-foreground">{PAYMENT_LABEL[order.payment.method]} · {order.payment.status}</span><strong>{formatM(order.total)}</strong></div><details className="mt-3"><summary className="cursor-pointer text-sm font-semibold text-primary">Order updates</summary><ol className="mt-3 space-y-2">{order.timeline.map((event,index)=><li key={`${event.at}-${index}`} className="flex justify-between gap-3 text-sm"><span>{event.status==="note"?event.note:ORDER_STATUS_LABEL[event.status as keyof typeof ORDER_STATUS_LABEL]??"Order placed"}</span><time className="shrink-0 text-muted-foreground">{new Date(event.at).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short"})}</time></li>)}</ol></details><Button className="mt-4" variant="outline" onClick={()=>{const r=s.reorder(order.id);setNotice(`${r.added} item${r.added===1?"":"s"} added to your cart.${r.unavailable.length?` Unavailable: ${r.unavailable.join(", ")}.`:""}${r.priceChanged.length?` Prices changed for: ${r.priceChanged.join(", ")}.`:""}`);}}>Order these again</Button></article>)}</div>:<Empty title="No orders yet" body="Your completed checkout will appear here." action="Start shopping"/>}</section>}
 {section==="favourites"&&<section><h2 className="text-xl font-semibold">Saved favourites</h2><p className="mb-4 text-sm text-muted-foreground">Your handy list of go-to groceries.</p>{s.favourites.length?<div className="divide-y rounded-2xl border bg-card">{s.favourites.map(id=>s.products.find(p=>p.id===id)).filter(Boolean).map(product=><div key={product!.id} className="flex items-center gap-3 p-4"><span className="grid size-12 place-items-center rounded-xl bg-muted text-2xl">{product!.emoji}</span><div className="flex-1"><p className="font-semibold">{product!.name}</p><p className="text-sm text-muted-foreground">{formatM(product!.promoPrice??product!.price)} / {product!.unit}</p></div><Button size="sm" onClick={()=>s.addToCart(product!)}>Add</Button><Button size="icon" variant="ghost" aria-label={`Remove ${product!.name} from favourites`} onClick={()=>s.toggleFavourite(product!.id)}><Heart className="size-4 fill-current text-primary"/></Button></div>)}</div>:<Empty title="No favourites saved" body="Tap the heart on a product to keep it here." action="Browse groceries"/>}</section>}
 {section==="preferences"&&<section className="max-w-2xl"><h2 className="text-xl font-semibold">Updates and reminders</h2><p className="mb-5 text-sm text-muted-foreground">Choose the messages that are useful to you.</p><div className="divide-y rounded-2xl border bg-card">{s.notificationPreferences.map(item=><label key={item.id} className="flex cursor-pointer items-center justify-between gap-4 p-4"><span><span className="block font-medium">{item.label}</span><span className="text-sm text-muted-foreground">{item.description}</span></span><input type="checkbox" checked={item.enabled} onChange={()=>s.toggleNotification(item.id)} className="size-5 accent-primary"/></label>)}</div><p className="mt-4 text-xs text-muted-foreground">Preferences are saved locally in this demo.</p></section>}
 </div></div></main>;
}
function AddressBook(){const s=useAppStore();const [editing,setEditing]=useState<DeliveryAddress>({area:s.shop.defaultDeliveryArea,address:"",label:"Home"});const [notice,setNotice]=useState("");const save=(e:React.FormEvent)=>{e.preventDefault();s.saveAddress({...editing,id:editing.id??crypto.randomUUID()});setEditing({area:s.shop.defaultDeliveryArea,address:"",label:"Home"});setNotice("Address saved.");};return <section><div className="mb-4"><h2 className="text-xl font-semibold">Saved addresses</h2><p className="text-sm text-muted-foreground">Use familiar landmarks and directions to help your driver.</p></div>{notice&&<p role="status" className="mb-3 text-sm text-primary">{notice}</p>}<div className="mb-5 space-y-3">{s.savedAddresses.map(a=><div key={a.id} className="flex items-start gap-3 rounded-xl border bg-card p-4"><MapPin className="mt-0.5 size-4 text-primary"/><div className="flex-1"><p className="font-semibold">{a.label||"Address"}</p><p className="text-sm">{a.address}, {a.area}</p>{a.landmark&&<p className="text-sm text-muted-foreground">Near {a.landmark}</p>}</div><Button variant="ghost" size="icon" aria-label={`Remove ${a.label??"address"}`} onClick={()=>s.removeAddress(a.id!)}><Trash2 className="size-4"/></Button><Button variant="outline" size="sm" onClick={()=>setEditing(a)}>Edit</Button></div>)}</div><form onSubmit={save} className="grid max-w-2xl gap-3 rounded-2xl bg-muted/50 p-4 sm:grid-cols-2"><h3 className="font-semibold sm:col-span-2">{editing.id?"Edit address":"Add an address"}</h3><Input aria-label="Address label" placeholder="Label, e.g. Home" value={editing.label??""} onChange={e=>setEditing({...editing,label:e.target.value})}/><select aria-label="Delivery area" className="rounded-lg border bg-background px-3" value={editing.area} onChange={e=>setEditing({...editing,area:e.target.value})}>{s.shop.deliveryAreas.map(a=><option key={a}>{a}</option>)}</select><Input required aria-label="House or street" placeholder="House / street / place name" value={editing.address} onChange={e=>setEditing({...editing,address:e.target.value})}/><Input aria-label="Landmark" placeholder="Nearby landmark" value={editing.landmark??""} onChange={e=>setEditing({...editing,landmark:e.target.value})}/><Input aria-label="Driver directions" placeholder="Directions for driver (optional)" value={editing.instructions??""} onChange={e=>setEditing({...editing,instructions:e.target.value})}/><Button className="sm:col-span-2">Save address</Button></form></section>;}
function Empty({title,body,action}:{title:string;body:string;action:string}){return <div className="rounded-2xl border border-dashed p-10 text-center"><ShoppingBag className="mx-auto size-8 text-muted-foreground"/><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-1 text-sm text-muted-foreground">{body}</p><Link to="/shop" className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-primary">{action}<ChevronRight className="size-4"/></Link></div>;}
