/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminDeliveriesRouteImport } from './routes/admin.deliveries'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as OperationsDispatchRouteImport } from './routes/operations.dispatch'
import { Route as OperationsInventoryRouteImport } from './routes/operations.inventory'
import { Route as OperationsPickingRouteImport } from './routes/operations.picking'
import { Route as OperationsSupportRouteImport } from './routes/operations.support'
import { Route as OrderConfirmationIdRouteImport } from './routes/order-confirmation.$id'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as DriverOrdersIdRouteImport } from './routes/driver.orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeliveriesRoute = AdminDeliveriesRouteImport.update({
  id: '/admin/deliveries',
  path: '/admin/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/admin/promotions',
  path: '/admin/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsDispatchRoute = OperationsDispatchRouteImport.update({
  id: '/operations/dispatch',
  path: '/operations/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsInventoryRoute = OperationsInventoryRouteImport.update({
  id: '/operations/inventory',
  path: '/operations/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsPickingRoute = OperationsPickingRouteImport.update({
  id: '/operations/picking',
  path: '/operations/picking',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsSupportRoute = OperationsSupportRouteImport.update({
  id: '/operations/support',
  path: '/operations/support',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationIdRoute = OrderConfirmationIdRouteImport.update({
  id: '/order-confirmation/$id',
  path: '/order-confirmation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/admin/orders/$id',
  path: '/admin/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/admin/products/$id',
  path: '/admin/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/admin/products/new',
  path: '/admin/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverOrdersIdRoute = DriverOrdersIdRouteImport.update({
  id: '/driver/orders/$id',
  path: '/driver/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/operations/dispatch': typeof OperationsDispatchRoute
  '/operations/inventory': typeof OperationsInventoryRoute
  '/operations/picking': typeof OperationsPickingRoute
  '/operations/support': typeof OperationsSupportRoute
  '/order-confirmation/$id': typeof OrderConfirmationIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/driver/orders/$id': typeof DriverOrdersIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/operations/dispatch': typeof OperationsDispatchRoute
  '/operations/inventory': typeof OperationsInventoryRoute
  '/operations/picking': typeof OperationsPickingRoute
  '/operations/support': typeof OperationsSupportRoute
  '/order-confirmation/$id': typeof OrderConfirmationIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/driver': typeof DriverIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/driver/orders/$id': typeof DriverOrdersIdRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/operations/dispatch': typeof OperationsDispatchRoute
  '/operations/inventory': typeof OperationsInventoryRoute
  '/operations/picking': typeof OperationsPickingRoute
  '/operations/support': typeof OperationsSupportRoute
  '/order-confirmation/$id': typeof OrderConfirmationIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/driver/orders/$id': typeof DriverOrdersIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/shop'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/deliveries'
    | '/admin/inventory'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/settings'
    | '/category/$slug'
    | '/operations/dispatch'
    | '/operations/inventory'
    | '/operations/picking'
    | '/operations/support'
    | '/order-confirmation/$id'
    | '/orders/$id'
    | '/product/$id'
    | '/admin/'
    | '/driver/'
    | '/orders/'
    | '/owner/'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/driver/orders/$id'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/shop'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/deliveries'
    | '/admin/inventory'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/settings'
    | '/category/$slug'
    | '/operations/dispatch'
    | '/operations/inventory'
    | '/operations/picking'
    | '/operations/support'
    | '/order-confirmation/$id'
    | '/orders/$id'
    | '/product/$id'
    | '/admin'
    | '/driver'
    | '/orders'
    | '/owner'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/driver/orders/$id'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/shop'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/deliveries'
    | '/admin/inventory'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/settings'
    | '/category/$slug'
    | '/operations/dispatch'
    | '/operations/inventory'
    | '/operations/picking'
    | '/operations/support'
    | '/order-confirmation/$id'
    | '/orders/$id'
    | '/product/$id'
    | '/admin/'
    | '/driver/'
    | '/orders/'
    | '/owner/'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/driver/orders/$id'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ShopRoute: typeof ShopRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDeliveriesRoute: typeof AdminDeliveriesRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  OperationsDispatchRoute: typeof OperationsDispatchRoute
  OperationsInventoryRoute: typeof OperationsInventoryRoute
  OperationsPickingRoute: typeof OperationsPickingRoute
  OperationsSupportRoute: typeof OperationsSupportRoute
  OrderConfirmationIdRoute: typeof OrderConfirmationIdRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductIdRoute: typeof ProductIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DriverIndexRoute: typeof DriverIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  DriverOrdersIdRoute: typeof DriverOrdersIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deliveries': {
      id: '/admin/deliveries'
      path: '/admin/deliveries'
      fullPath: '/admin/deliveries'
      preLoaderRoute: typeof AdminDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/admin/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/dispatch': {
      id: '/operations/dispatch'
      path: '/operations/dispatch'
      fullPath: '/operations/dispatch'
      preLoaderRoute: typeof OperationsDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/inventory': {
      id: '/operations/inventory'
      path: '/operations/inventory'
      fullPath: '/operations/inventory'
      preLoaderRoute: typeof OperationsInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/picking': {
      id: '/operations/picking'
      path: '/operations/picking'
      fullPath: '/operations/picking'
      preLoaderRoute: typeof OperationsPickingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/support': {
      id: '/operations/support'
      path: '/operations/support'
      fullPath: '/operations/support'
      preLoaderRoute: typeof OperationsSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation/$id': {
      id: '/order-confirmation/$id'
      path: '/order-confirmation/$id'
      fullPath: '/order-confirmation/$id'
      preLoaderRoute: typeof OrderConfirmationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/admin/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/admin/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/admin/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/orders/$id': {
      id: '/driver/orders/$id'
      path: '/driver/orders/$id'
      fullPath: '/driver/orders/$id'
      preLoaderRoute: typeof DriverOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ShopRoute: ShopRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDeliveriesRoute: AdminDeliveriesRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  CategorySlugRoute: CategorySlugRoute,
  OperationsDispatchRoute: OperationsDispatchRoute,
  OperationsInventoryRoute: OperationsInventoryRoute,
  OperationsPickingRoute: OperationsPickingRoute,
  OperationsSupportRoute: OperationsSupportRoute,
  OrderConfirmationIdRoute: OrderConfirmationIdRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductIdRoute: ProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  DriverIndexRoute: DriverIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  DriverOrdersIdRoute: DriverOrdersIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
